### ISSUE TITLE
bugfix; ImportError: cannot import name build_ext

### ISSUE THREAD

**Issue by drtrigon** [xlfe/PJON-cython#2]
I tried to install/compile PJON-python without success.

1. If I try to clone it from git I get this:
```
osboxes@osboxes:~$ git clone https://github.com/xlfe/PJON-cython
Cloning into 'PJON-cython'...
remote: Counting objects: 99, done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 99 (delta 33), reused 92 (delta 28), pack-reused 0
Unpacking objects: 100% (99/99), done.
Checking connectivity... done.
osboxes@osboxes:~$ cd PJON-cython/
osboxes@osboxes:~/PJON-cython$ python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import build_ext
ImportError: cannot import name build_ext
osboxes@osboxes:~/PJON-cython$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import build_ext
ImportError: cannot import name build_ext
osboxes@osboxes:~/PJON-cython$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import build_ext
ImportError: cannot import name build_ext
```
2. If I try it via pip:
```
osboxes@osboxes:~/PJON-cython$ sudo pip install pjon-cython
Downloading/unpacking pjon-cython
  Downloading pjon_cython-11.1.0.tar.gz (466kB): 466kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pjon-cython/setup.py) egg_info for package pjon-cython
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pjon-cython/setup.py", line 2, in <module>
        from Cython.Build import build_ext
    ImportError: cannot import name build_ext
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pjon-cython/setup.py", line 2, in <module>

    from Cython.Build import build_ext

ImportError: cannot import name build_ext

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pjon-cython
Storing debug log for failure in /home/osboxes/.pip/pip.log
```

Further if I replace `setup.py` with this one:
```
from distutils.core import setup
from Cython.Build import cythonize

std_args =['-std=c++11', '-DLINUX']

setup(
    ext_modules = cythonize("pjon_cython/pjon_cython.pyx")
)
```
it starts complaining about c++: `pjon_cython/pjon_cython.pyx:78:23: Operation only allowed in c++` etc.

This was all done using Python 2.7.6.

**Comment by xlfe** [comment]
Thanks for the bug report - I will fix this up in the next couple of days. Sorry for the delay

**Comment by xlfe** [comment]
@drtrigon I've just pushed a bugfix 11.1.1 to pip and to master - would you mind trying again please?

Thanks

**Comment by drtrigon** [comment]
Install and build works now but running the test results in:
> osboxes@osboxes:~/PJON-cython$ python pjon-cython-testing.py 
Traceback (most recent call last):
  File "pjon-cython-testing.py", line 4, in <module>
    class GlobalUDP(PJON.GlobalUDP):
AttributeError: 'module' object has no attribute 'GlobalUDP'

Even though GlobalUDP and LocalUDP are listed in the .pyx and .cpp files, doing a dir for the module imported gives:
> ['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']

**Comment by xlfe** [comment]
Thanks @drtrigon  - bugfix pushed to repo and pypi - please try again thanks!

**Comment by drtrigon** [comment]
Thanks @xlfe it works from git repo now - I did not test the pip install assuming this will work too then. Thanks a lot for your work, however I found a few things that would be good to have (please):
* can you add the constants as they are missing, e.g.: PJON_ACK, PJON_NAK, PJON_BUSY, PJON_FAIL, PJON_BROADCATS, etc. - I tested the technique mentioned in the last post of https://stackoverflow.com/questions/31766219/export-constants-from-header-with-cython and it works
* can you add `bus.update()` and `ret = bus.receive(1000)` (a receive that returns the state)
* how can I use the error handler (introduced in https://github.com/xlfe/PJON-cython/commit/ac2a00544bcf4dc0b838bc050528f00de07217fc) ?
* <s>can you add a note that this current release works with PJON 11.1 only - as it does not compile with older code</s> (@gioblu can we integrate PJON-cython into PJON codebase directly?)

**Comment by gioblu** [comment]
Ciao @drtrigon thank you for your support to the PJON and PJON-cython projects.
By my side there is no problem to add it to the original PJON repo, although the decision is of @xlfe , and also being different languages we should consider if it has sense and how to organize the project structure to eventually host other languages implementations and tools.

**Comment by drtrigon** [comment]
I agree @xlfe has to decide too. I my opinion - as a user - it would be great to have "officially supported" bindings to other languages (namely python in this case) included with the PJON distribution. That would also follow the python philosophy of "batteries included" (see e.g. PEP 2, 206, etc).

**Comment by xlfe** [comment]
@drtrigon @gioblu I've just uploaded 11.1.4 - which has much better consistency with PJON in terms of how it operates. I have added heaps of additional tests and updated the README.md with examples of how (@drtrigon) you can access the various return values, exceptions, etc...

In terms of moving this code into the main PJON repo I am happy maintaining it here for now - as it is open source @gioblu is of course welcome to do with it as he wishes, including fork it himself (as is anyone).

just my 2c

As always, thanks for the feedback / suggestions!

**Comment by gioblu** [comment]
Ciao @xlfe compliments for the great work and your support catching those bugs 🥇. I think clear and visible links to this repo in the PJON README, headers and wiki will be the way to go. I do agree that it is for you more handy and in general a more consistent choice (being different languages) to maintain it separately. 

Will push your last suggested change and run the PJON-cython examples.

Thank you :)

**Comment by drtrigon** [comment]
Thanks @xlfe for your work! The constants work now very nicely!

However the test results in:
> .../PJON-cython$ python setup.py nosetests --with-doctest --doctest-extension=md
/usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'compiler_directives'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running nosetests
running egg_info
creating pjon_cython.egg-info
writing pjon_cython.egg-info/PKG-INFO
writing top-level names to pjon_cython.egg-info/top_level.txt
writing dependency_links to pjon_cython.egg-info/dependency_links.txt
writing manifest file 'pjon_cython.egg-info/SOURCES.txt'
reading manifest file 'pjon_cython.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'PJON'
no previously-included directories found matching 'PJON/examples'
no previously-included directories found matching 'PJON/devices'
no previously-included directories found matching 'PJON/documentation'
no previously-included directories found matching 'PJON/specification'
no previously-included directories found matching 'PJON/trademark'
writing manifest file 'pjon_cython.egg-info/SOURCES.txt'
skipping 'pjon_cython/_pjon_cython.cpp' Cython extension (up-to-date)

and freezes at this point... stopping yields:
> Ran 0 tests in 437.148s

**Comment by xlfe** [comment]
Hmm - that's odd. Here's what I get - it looks like yours is stopping at the build step. 

What's the output you get when you do a pip install (which presumably runs the build step successfully)?

```bash
$ python setup.py nosetests
...python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'compiler_directives'
  warnings.warn(msg)
running nosetests
running egg_info
writing pjon_cython.egg-info/PKG-INFO
writing top-level names to pjon_cython.egg-info/top_level.txt
writing dependency_links to pjon_cython.egg-info/dependency_links.txt
reading manifest file 'pjon_cython.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'PJON/examples'
no previously-included directories found matching 'PJON/devices'
no previously-included directories found matching 'PJON/documentation'
no previously-included directories found matching 'PJON/specification'
no previously-included directories found matching 'PJON/trademark'
writing manifest file 'pjon_cython.egg-info/SOURCES.txt'
skipping 'pjon_cython/_pjon_cython.cpp' Cython extension (up-to-date)
building 'pjon_cython._pjon_cython' extension
creating build
...
clang ...
clang++ ...
............
----------------------------------------------------------------------
Ran 12 tests in 4.910s

OK
```

**Comment by drtrigon** [comment]
I'll test this as soon as I can ... might it be related to files (.py, .sh) created in the same dir as setup.py resides?


Am 26. September 2018 03:36:22 MESZ schrieb Felix <notifications@github.com>:

**Comment by xlfe** [comment]
@drtrigon not sure sorry - I run the tests across python versions with and without Cython before each release - see attached
[log-e2f77910-9234-4b37-93ec-1e0f1992d901.txt](https://github.com/xlfe/PJON-cython/files/2430140/log-e2f77910-9234-4b37-93ec-1e0f1992d901.txt)

**Comment by drtrigon** [comment]
```
$ python setup.py nosetests
/usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'compiler_directives'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running nosetests
running egg_info
creating pjon_cython.egg-info
writing pjon_cython.egg-info/PKG-INFO
writing top-level names to pjon_cython.egg-info/top_level.txt
writing dependency_links to pjon_cython.egg-info/dependency_links.txt
writing manifest file 'pjon_cython.egg-info/SOURCES.txt'
reading manifest file 'pjon_cython.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'PJON'
no previously-included directories found matching 'PJON/examples'
no previously-included directories found matching 'PJON/devices'
no previously-included directories found matching 'PJON/documentation'
no previously-included directories found matching 'PJON/specification'
no previously-included directories found matching 'PJON/trademark'
writing manifest file 'pjon_cython.egg-info/SOURCES.txt'
skipping 'pjon_cython/_pjon_cython.cpp' Cython extension (up-to-date)
..F...F.....
======================================================================
FAIL: Test ThroughSerial and send_repeatedly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osboxes/sketchbook/OWPJON/PJON-cython/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/osboxes/sketchbook/OWPJON/PJON-cython/test/test.py", line 43, in test_throughserial
    ts = ThroughSerial(44, b"/dev/null", 115200)
  File "pjon_cython/_pjon_cython.pyx", line 310, in pjon_cython._pjon_cython.ThroughSerial.__init__
    assert self.bus.strategy.can_start()
AssertionError

======================================================================
FAIL: Check that we get PACKET_BUFFER_FULL error in ThroughSerial
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osboxes/sketchbook/OWPJON/PJON-cython/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/osboxes/sketchbook/OWPJON/PJON-cython/nose-1.3.7-py2.7.egg/nose/tools/nontrivial.py", line 60, in newfunc
    func(*arg, **kw)
  File "/home/osboxes/sketchbook/OWPJON/PJON-cython/test/test.py", line 88, in test_ts_raises_packet_buffer_full
    ts = ThroughSerial(44, b"/dev/null", 115200)
  File "pjon_cython/_pjon_cython.pyx", line 310, in pjon_cython._pjon_cython.ThroughSerial.__init__
    assert self.bus.strategy.can_start()
AssertionError

----------------------------------------------------------------------
Ran 12 tests in 54.039s

FAILED (failures=2)
```
the tests run now - my issue was your suggestion here https://github.com/xlfe/PJON-cython#testing as I used:
> $ python setup.py nosetests --with-doctest --doctest-extension=md

in more detail using `--with-doctest` freezes the tests for me. Hope this helps.

**Comment by xlfe** [comment]
Ah ok I'll look into that problem with the doc test. Thanks.

Try upgrading to the latest version as I've fixed a few bugs in the past
few days (including the assertion error you're getting there)

**Comment by drtrigon** [comment]
```
$ python setup.py nosetests
/usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'compiler_directives'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running nosetests
running egg_info
creating pjon_cython.egg-info
writing pjon_cython.egg-info/PKG-INFO
writing top-level names to pjon_cython.egg-info/top_level.txt
writing dependency_links to pjon_cython.egg-info/dependency_links.txt
writing manifest file 'pjon_cython.egg-info/SOURCES.txt'
reading manifest file 'pjon_cython.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'PJON'
no previously-included directories found matching 'PJON/examples'
no previously-included directories found matching 'PJON/devices'
no previously-included directories found matching 'PJON/documentation'
no previously-included directories found matching 'PJON/specification'
no previously-included directories found matching 'PJON/trademark'
writing manifest file 'pjon_cython.egg-info/SOURCES.txt'
skipping 'pjon_cython/_pjon_cython.cpp' Cython extension (up-to-date)
..................
----------------------------------------------------------------------
Ran 18 tests in 55.426s

OK
```

**Comment by drtrigon** [comment]
Nice! So finally I was able to port my original c++ code to python:
- c++: https://github.com/drtrigon/sketchbook/blob/master/OWPJON/LINUX/Local/LocalUDP/RemoteWorker/DeviceGeneric/DeviceGeneric.cpp
- python: https://github.com/drtrigon/sketchbook/blob/master/OWPJON/PJON-cython/DeviceGeneric.py
